### ISSUE TITLE
TextKey - Unit issue

### ISSUE THREAD

**Issue by jardicc** [simonhenke/photoshop-types#5]
Text key has many distance units. But many of them might be more than PointValue only. Can be pixel value and others.

**Comment by simonhenke** [comment]
Good point, some of them are probably false. Some fields in PS accept only one unit and others do take all, so I probably just assumed Points is the standard for some text properties. Do you already have a list of which props are falsely typed? Otherwise I'd have to test them all one by one.

**Comment by jardicc** [comment]
I think you could change PS units. And take snapshot for each unit. And then compare. Alchemist has difference view.

There is also an option that action accepts different units correctly but the getter will always return one specific unit.

**Comment by simonhenke** [comment]
I just tested some properties (font size, leading, baseline shift) and I don't think that they can have any different unit than `pointsUnit`. It is possible to enter values in different units such as px and mm, but that doesn't even get reflected in the Action Descriptor. The conversion is done beforehand by Photoshop, so the ActionDescriptor already has the according points value.
