### ISSUE TITLE
Missing history class

### ISSUE THREAD

**Issue by jardicc** [simonhenke/photoshop-types#6]
It would be also cool to have typings for History steps/Snapshots and their properties.

**Comment by simonhenke** [comment]
I can add them next week 👍 
If I remember correctly I even wrote some of these types or parts of it for a project, maybe I just didn't add them to the types repo.

**Comment by jardicc** [comment]
Perfect! Later we could create some "getter" library in TypeScript. I could add a new code generation tab into Alchemist for that if that would make sense.

**Comment by simonhenke** [comment]
Sounds good! I already have some quite generic getter for the app, document and layer:

```
export function getLayerProperty<T extends keyof LayerDescriptor>(_property: T, targetProperty?: TargetProperty): LayerDescriptor[T] {
  return photoshop.action.batchPlay([
    {
      _obj: 'get',
      _target: [
        { _property },
        {
          _ref: 'layer',
          ...(targetProperty ? {...targetProperty} : {_enum: 'ordinal', _value: 'targetEnum'}),
        }
      ]
    },
  ], { synchronousExecution: true })[0][_property]
}
```
The naming might be a bit confusing, targetProperty can be `{_index: 1}`, `{_name: 'test'}` etc.

In which way did you plan to integrate the getter functionality in the UI?

**Comment by jardicc** [comment]
You would click "Add" when you select e.g. Layer + Property

And it would generate something like: 
```
import {getLayerDescByID} from "uxp-ps-getter";
const soMore = getLayerDescByID(7,"smartObjectMore");
```

**Comment by simonhenke** [comment]
That could work 👍 I think a dropdown to select targetEnum/index/name/id/offset would be nice then, to specify the target of the getter more detailed.

**Comment by jardicc** [comment]
Yes, I wanted to have an option for reference but Alchemist was already complex enough :-D And to me, it wasn't clear whether this data should be part of descriptor options or part of recording settings as you suggesting. And for some actions, there is no reference or it is a reference mix and it is unclear. But for getters, it shouldn't be difficult.

**Comment by simonhenke** [comment]
Haha I know that feeling. And the user is probably already overwhelmed by the interface anyways. At least on the code side, which really helped me make the complexity more manageable in my recent projects, was to integrate Redux - but I think you're already using it aren't you? Definitely makes sense for a complex to like Alchemist where a lot of state is shared.

I was also wondering where such an option or such data would fit best... And if there was a library providing all sorts of functionality , the user maybe wouldn't even need an interface for that. He could just use intelliSense and start typing "getSmartObjectMore".
I do have such helper files in my projects with really many functions for all kinds of use cases, but I haven't really packaged them for reuse yet, so they just fly around in every project. (I briefly tried once, but the import didn't quite work as I expected).

And I agree, getters are really the easiest part here as they're all structured in the same way and can be easily generalized. Setters might be feasible, too, by making use of subset types etc. 
Actions however are a totally different story. For example you could have a `transform()` function with all the possible parameters which might be confusing/overwhelming for the user, or a `translate()` function with just an x and y parameter. Under the hood both use the same event though...

**Comment by jardicc** [comment]
Alchemist does use Redux. Redux DevTools was an inspiration for Alchemist and also I forked some of its components and changed them. E.g. Tree view.

**Comment by simonhenke** [comment]
I've added types for a history state.
